export const SET_FIRST_OPEN = 'app/SET_FIRST_OPEN';
export const SET_GLOBAL_NOTIFICATION = 'app/SET_GLOBAL_NOTIFICATION';
export const SET_GEOLOCATION = 'app/SET_GEOLOCATION';
export const SET_PUSH_NOTIFICATION_IDS = 'app/SET_PUSH_NOTIFICATION_IDS';
export const SET_ADMOB_ID = 'app/SET_ADMOB_ID';
export const SET_ADVERTISEMENTS = 'app/SET_ADVERTISEMENTS';
export const SET_EVALUATED = 'app/SET_EVALUATED';